# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  cognivaultapiidentity:
    image: cognivaultapiidentity
    build:
      context: .
      dockerfile: source/CogniVault.Api.Identity/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5166:5166
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
