# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.8'

services:
  cognivaultapiidentity:
    image: identity
    build:
      context: .
      dockerfile: source/CogniVault.Api.Identity/Dockerfile
    ports:
      - 5166:5166
      - 7166:7166  # Mapping the HTTPS port from the host to the container
    environment:
      - ASPNETCORE_URLS=http://+:5166;https://+:7166;
      - ASPNETCORE_HTTPS_PORT=7166
      - ASPNETCORE_Kestrel__Certificates__Default__Password=misterpalmer
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cognivault.pfx
    volumes:
      - ./cognivault.pfx:/https/cognivault.pfx:ro  # Mounting the certificate from the host to the container
    networks:
      - default
  cognivaultapifilemanager:
    image: filemanager
    build:
      context: .
      dockerfile: source/CogniVault.Api.FileManager/Dockerfile
    ports:
      - 5167:5167
      - 7167:7167  # Mapping the HTTPS port from the host to the container
    environment:
      - ASPNETCORE_URLS=http://+:5167;https://+:7167;
      - ASPNETCORE_HTTPS_PORT=7167
      - ASPNETCORE_Kestrel__Certificates__Default__Password=misterpalmer
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cognivault.pfx
      - IDENTITY_API_URL=http://identity:7166
    volumes:
      - ./cognivault.pfx:/https/cognivault.pfx:ro  # Mounting the certificate from the host to the container
    depends_on:
      - cognivaultapiidentity
    networks:
      - default
networks:
  default:
      name: cognivault
      external: false