# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.8'

services:
  cognivaultapiidentity:
    image: identity
    build:
      context: .
      dockerfile: source/CogniVault.Api.Identity/Dockerfile
    ports:
      - 7166:443  # Mapping the HTTPS port from the host to the container
    environment:
      - ASPNETCORE_URLS=https://+:443;
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password="CogniVaultWebUI"
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/LocalhostCogniVaultWebUI.pfx
    volumes:
      - ./.certs/LocalhostCogniVaultWebUI.pfx:/https/LocalhostCogniVaultWebUI.pfx:ro  # Mounting the certificate from the host to the container
    networks:
      - default
  cognivaultapifilemanager:
    image: filemanager
    build:
      context: .
      dockerfile: source/CogniVault.Api.VirtualFileSystem/Dockerfile
    ports:
      - 7167:443  # Mapping the HTTPS port from the host to the container
    environment:
      - ASPNETCORE_URLS=https://+:443;
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password="CogniVaultWebUI"
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/LocalhostCogniVaultWebUI.pfx
      - IDENTITY_API_URL=http://cognivaultapiidentity:443
    volumes:
      - ./.certs/LocalhostCogniVaultWebUI.pfx:/https/LocalhostCogniVaultWebUI.pfx:ro  # Mounting the certificate from the host to the container
    depends_on:
      - cognivaultapiidentity
    networks:
      - default
networks:
  default:
      name: cognivault
      external: false