@startuml
interface IResourceManager {
    SetPermissions(resource:IResource, permission:IPermission) : void
    GetPermissions(resource:IResource) : IPermission
}
IResourceManager --> "Root" IDirectory
IResourceManager --> "DirectoryOperations" IResourceOperation
IResourceManager --> "FileOperations" IResourceOperation
@enduml
