@startuml
class UsernameEncryptor {
    - <<const>> SaltSize : int = 32
    + Encrypt(password:string) : string
    + Verify(combinedSaltAndPassword:string, passwordToVerify:string) : bool
    - GenerateSalt(size:int) : byte[]
    - HashPassword(password:byte[], salt:byte[]) : byte[]
}
IUsernameEncryptor <|-- UsernameEncryptor
@enduml
