@startuml
class Password {
    + Value : string <<get>>
    + Password(value:string, validator:IPasswordValidator, encryptor:IPasswordEncryptor)
    + Verify(passwordToVerify:string) : bool
    + Equals(other:Password) : bool
    + <<override>> Equals(obj:object) : bool
    + <<override>> GetHashCode() : int
    + <<override>> ToString() : string
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<Password>" <|-- Password
Password --> "validator" IPasswordValidator
Password --> "encryptor" IPasswordEncryptor
@enduml
