@startuml
class FileOperations {
    + Create(name:ResourceName, user:IUser) : void
    + Delete(name:ResourceName) : void
    + Get(name:ResourceName) : IResource
    + Update(name:ResourceName, newEntity:IResource) : void
}
IResourceOperation <|-- FileOperations
@enduml
