@startuml
class UserPermission {
    + GrantedGroup : IGroup? <<get>>
    + UserPermission(type:PermissionType, grantedUser:IUser)
}
IPermission <|-- UserPermission
UserPermission --> "Type" PermissionType
UserPermission --> "GrantedUser" IUser
@enduml
